// Roll list for 10th HI — roll number = index position (1-based)
export const rollList = [
  { rollNo: 1,  name: 'Aditya Gupta' },
  { rollNo: 2,  name: 'Shreya' },
  { rollNo: 3,  name: 'Shourya' },
  { rollNo: 4,  name: 'Mihika' },
  { rollNo: 5,  name: 'Anuraj' },
  { rollNo: 6,  name: 'Parth' },
  { rollNo: 7,  name: 'Ravi' },
  { rollNo: 8,  name: 'Ruchir' },
  { rollNo: 9,  name: 'Sonali' },
  { rollNo: 10, name: 'Yesh' },
  { rollNo: 11, name: 'Isha' },
  { rollNo: 12, name: 'Ayush' },
  { rollNo: 13, name: 'Aman Kishor' },
  { rollNo: 14, name: 'Kirti' },
  { rollNo: 15, name: 'Suryanahu' },
  { rollNo: 16, name: 'Mohit' },
  { rollNo: 17, name: 'Virat Singh' },
  { rollNo: 18, name: 'Rudransh' },
  { rollNo: 19, name: 'Sushant' },
  { rollNo: 20, name: 'Arnav' },
  { rollNo: 21, name: 'Deepanshu' },
  { rollNo: 22, name: 'Anshuka' },
  { rollNo: 23, name: 'Utkarsh' },
  { rollNo: 24, name: 'Vibhav' },
  { rollNo: 25, name: 'Aadarsh' },
  { rollNo: 26, name: 'Sahil' },
  { rollNo: 27, name: 'Ayush Kumar' },
  { rollNo: 28, name: 'Awni' },
  { rollNo: 29, name: 'Aditya Prakash' },
  { rollNo: 30, name: 'Abhigyan' },
  { rollNo: 31, name: 'Anushka' },
  { rollNo: 32, name: 'Shivam' },
  { rollNo: 33, name: 'Chirag' },
  { rollNo: 34, name: 'Khushi' },
  { rollNo: 35, name: 'Pratyaksh' },
  { rollNo: 36, name: 'Rahul' },
  { rollNo: 37, name: 'Manshi' },
  { rollNo: 38, name: 'Shivansh' },
  { rollNo: 39, name: 'Abhishek' },
  { rollNo: 40, name: 'Utkarsh Bhardwaj' },
];
